---
title: Elections - Kendall County Local Governments
---

<script src="lib/core-js-2.5.3/shim.min.js"></script>
<script src="lib/react-18.2.0/react.min.js"></script>
<script src="lib/react-18.2.0/react-dom.min.js"></script>
<script src="lib/reactwidget-1.0.0/react-tools.js"></script>
<script src="lib/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="lib/reactable-0.4.4/reactable.css" rel="stylesheet"/>
<script src="lib/reactable-binding-0.4.4/reactable.js"></script>

<br>


<hr>

Relatively few citizens choose to run for public office in Kendall County. While well-salaried elected positions often have multiple people line up to run, those positions with nominal stipends (e.g. city council) or which are entirely unpaid (e.g. school board) often go uncontested. For now, I'm including election information just on these nominally/unpaid positions. 

<hr>

<br>

## Upcoming Elections to File For Candidacy

<hr/>

### 02 May 2026 Local Elections
<br>

#### Boerne ISD
<details>
<summary style="font-size: 1.15em;">Trustee, Place 6</summary>

- Current Office Holder: Kristi Schmidt<sup>[1](#fn1)</sup>
- First Gained Office: 6 May 2023 Election (Unopposed)
- Election History
	- 6 May 2023 Election (Unopposed)
		- Certified by BISD Board Action in lieu of Election<sup>[2](#fn2)</sup>

</details>

<details>
<summary style="font-size: 1.15em;">Trustee, Place 7</summary>
- Current Office Holder: Rich Sena<sup>[1](#fn1)</sup>
- First Gained Office: 10 May 2014 Election
- Election History
	- 6 May 2023 Election (Unopposed)
		- Certified by BISD Board Action in lieu of Election<sup>[2](#fn2)</sup>
	- 2 May 2020 Election (Unopposed)
		- Certified by BISD Board Action in lieu of Election<sup>[3](#fn3)</sup>
	- 6 May 2017 Election<sup>[4](#fn4)</sup>
		- Opposed by Mike Hogan
		- Won 81.5% (1,508 votes) to 18.5% (342 votes) 
	- 10 May 2014 Election (Unopposed)
	  - Certified by BISD Board Action in lieu of Election<sup>[5](#fn5)</sup>
</details>


<br>

#### City of Boerne

<!-- <details> -->
<!-- <summary style="font-size: 1.15em;">Mayor</summary> -->

<!-- - Current Office Holder: Frank Ritchie<sup>[7](#fn7)</sup> -->
<!-- - First Gained Office: 06 May 2023 Election -->
<!-- - Election History -->
<!-- 	- 06 May 2023 Election<sup>[8](#fn8)</sup> -->
<!-- 		- Opposed by Nina Woolard -->
<!-- 		- Won 75.96% (1,577 votes) to 24.04% (499 votes) -->

<!-- </details> -->
<!-- <details> -->
<!-- <summary style="font-size: 1.15em;">Council Member, District 2</summary> -->

<!-- - Current Office Holder: Sharon D. Wright<sup>[9](#fn9)</sup> -->
<!-- - First Gained Office: 06 May 2023 Election -->
<!-- - Election History -->
<!-- 	- 06 May 2023 Election<sup>[8](#fn8)</sup> -->
<!-- 		- Opposed by Joe Bateman -->
<!-- 		- Won 52.17% (252 votes) to 47.83% (231 votes) -->

<!-- </details> -->
<!-- <details> -->
<!-- <summary style="font-size: 1.15em;">Council Member, District 4</summary> -->

<!-- - Current Office Holder: Bret Bunker<sup>[9](#fn9)</sup> -->
<!-- - First Gained Office: 10 Oct 2023 - Appointed to fill vacant seat<sup>[10](#fn10)</sup> -->

<!-- </details> -->

<details>
<summary style="font-size: 1.15em;">Council Member, District 1</summary>

- Current Office Holder: Ty Wolosin<sup>[6](#fn6)</sup>
- First Gained Office: Appointed December 2018<sup>[7](#fn7)</sup>
- Election History
  - 04 May 2024 Election<sup>[8](#fn8)</sup>
    - Opposed by Jeremy Pratt
    - Won 63.77% (257 votes) to 36.23% (146 votes)
  - 07 May 2022 Election (Unopposed)<sup>[9](#fn9)</sup>
  - 2020 May Election (Unopposed)

</details>

<details>
<summary style="font-size: 1.15em;">Council Member, District 3</summary>

- Current Office Holder: *Vacant*
  - Quinten Scott resigned this position on 22 July 2025<sup>[10](#fn10)</sup>
</details>

<details>
<summary style="font-size: 1.15em;">Council Member, District 5</summary>

- Current Office Holder: Joseph Macaluso<sup>[6](#fn9)</sup>
- First Gained Office: May 2020 Election (Unopposed)
- Election History
  - 2024 Election<sup>[8](#fn8)</sup>
    - Opposed by Nick Nuth
    - Won 67.93% (250 votes) to 32.07% (118 votes)
  - 07 May 2022 Election (Unopposed)<sup>[9](#fn9)</sup>
  - 2020 May Election (Unopposed)
</details>



<br>


### 08 Nov 2026 Local Elections
<br/>

#### Comfort ISD
<details>
<summary style="font-size: 1.15em;">Trustee, District 1</summary>

- Current Office Holder: Larry Thayn<sup>[11](#fn11)</sup>

</details>

<details>
<summary style="font-size: 1.15em;">Trustee, District 2</summary>

- Current Office Holder: Alison Judkins<sup>[11](#fn11)</sup>

</details>

<details>
<summary style="font-size: 1.15em;">Trustee, District 3</summary>

- Current Office Holder: Lilly Edwards<sup>[11](#fn11)</sup>

</details>

<details>
<summary style="font-size: 1.15em;">Trustee, District 4</summary>

- Current Office Holder: Shauna Stransky<sup>[11](#fn11)</sup>

</details>

<details>
<summary style="font-size: 1.15em;">Trustee, District 7</summary>

- Current Office Holder: Wesley Holekamp<sup>[11](#fn11)</sup>

</details>


<br>


<!-- #### City of Fair Oaks Ranch -->
<!-- <details> -->
<!-- <summary style="font-size: 1.15em;">Council Member, Place 3</summary> -->

<!-- - Current Office Holder: Ruben J. Olvera<sup>[11](#fn11)</sup> -->
<!-- - First Gained Office: 09 Dec 2023 Election -->
<!-- - Election History -->
<!-- 	- 09 Dec 2023 Election (Special Election to Fill Vacant Seat)<sup>[12](#fn12)</sup> -->
<!-- 		- Opposed by Vincent Caldarola -->
<!-- 		- Won 85.79% (489 votes) to 14.21% (81 votes) -->


<!-- </details> -->
<!-- <details> -->
<!-- <summary style="font-size: 1.15em;">Council Member, Place 4</summary> -->

<!-- - Current Office Holder: Laura Koerner<sup>[11](#fn11)</sup> -->
<!-- - First Gained Office:  -->
<!-- - Election History -->
<!-- 	- 07 May 2022 Election (Unopposed)<sup>[14](#fn14)</sup> -->
<!-- 	- 06 May 2019 Election (Unopposed)<sup>[13](#fn13)</sup> -->

<!-- </details> -->
<!-- <details> -->
<!-- <summary style="font-size: 1.15em;">Council Member, Place 5</summary> -->

<!-- - Current Office Holder: Scott Parker<sup>[11](#fn11)</sup> -->
<!-- - First Gained Office:  -->
<!-- - Election History -->
<!-- 	- 07 May 2022 Election (Unopposed)<sup>[14](#fn14)</sup> -->
<!-- 	- 01 May 2021 Election (Special Election to Fill Vacant Seat)<sup>[15](#fn15)</sup> -->
<!-- 	 	- Opposed by J.C. Taylor and Tim Corey -->
<!-- 		- Obtained 37.73% (907 votes) to Taylor's 49.42% (1,188 votes) and Corey's 12.85% (309 votes) -->
<!-- 		- Since no candidate obtained 50% of the vote, result triggered a runoff election -->
<!-- 		- Taylor withdrew his candidacy from the runoff election -->
<!-- 		- Per Texas Election Code, if a runoff candidate withdraws, the remaining candidate is considered to be elected -->

<!-- </details> -->


<br>
<br>

## Election Details by Entity

<hr/>

<!-- ### Kendall County -->

<!-- <details> -->
<!--   <summary style="font-size: 1.25em;">Important Election Dates</summary> -->

<!-- - November 5th, 2024 General Election -->
<!-- 	- <span style="font-style: italic;">&ast;&ast;&ast;It is past the allowable time to file as a candidate for any county race for the November General Election.&ast;&ast;&ast;</span> -->
<!-- 	- <span style="font-style: italic;">I will update county elections for 2025 sometime after the 2024 General Election.</span> -->
<!-- </details> -->

<!-- <details> -->
<!--   <summary style="font-size: 1.25em;">Process to File</summary> -->
<!-- </details> -->

<!-- <details> -->
<!--   <summary style="font-size: 1.25em;">Positions Up for Election</summary> -->
<!-- </details> -->


<!-- <br/> -->

### Boerne ISD


<details>
  <summary style="font-size: 1.25em;">Important Election Dates</summary>

- **14 Jan 2026** - First Day to File for Place on Ballot  
- **Feb 2025** - Boerne ISD typically holds a Board Candidate Workshop in early February for prospective candidates to learn about the process. Notices for all BISD public meetings are posted to [BoardBook](https://meetings.boardbook.org/Public/Organization/1350). 
- **13 Feb 2026** - Last Day to File for Candidacy
- **20 Apr 2026** - First Day of Early Voting by Personal Appearance
- **28 Apr 2026** - Last Day of Early Voting by Personal Appearance
- **02 May 2026** - Local Election
</details>
<details>
  <summary style="font-size: 1.25em;">Process to File</summary>

- Ensure you meet eligibility requirements: [Secretary of State - Qualifications](https://www.sos.state.tx.us/elections/laws/qualifications.shtml)
	- Basically...
		- Be a U.S. citizen living in the state for at least 12 months
		- Lived in the district at least 6 months
		- Don't be a felon or mentally incapacitated
- Complete a physical copy of the application: [Secretary of State - PDF](https://www.sos.state.tx.us/elections/forms/pol-sub/2-49f.pdf)
- Deliver completed application to Boerne ISD no later than <span style="text-decoration: underline;">**5:00pm, 13 Feb 2026**</span>.
	- Address: 235 Johns Rd, Boerne, TX 78006
- Contact for Questions:
	- Phone: 830-357-2000
	- Email: bisdelection@boerneisd.net

</details> 
<details>
  <summary style="font-size: 1.25em;">Positions Up for Election</summary>

<div style="margin-left:20px">
<!-- <br> -->
<!-- <span style="font-style: italic; font-size: 1.25em;">May 2025</span> -->

<!-- <details> -->
<!-- <summary style="font-size: 1.15em;">Trustee, Place 4</summary> -->

<!-- - Current Office Holder: Maritza Gonzalez-Cooper<sup>[1](#fn1)</sup> -->
<!-- - First Gained Office: 11 May 2013 Election -->
<!-- - Election History -->
<!-- 	- 11 May 2013 Election (Unopposed)<sup>[2](#fn2)</sup> -->
<!-- 	- 07 May 2016 Election (Unopposed)<sup>[3](#fn3)</sup> -->
<!-- 	- 04 May 2019 Election (Unopposed)<sup>[4](#fn4)</sup> -->
<!-- 	- 07 May 2022 Election<sup>[5](#fn5)</sup> -->
<!-- 		- Opposed by Armando Trevino -->
<!-- 		- Won 63.8% (3,135 votes) to 36.2% (1,796 votes) -->

<!-- </details> -->
<!-- <details> -->
<!-- <summary style="font-size: 1.15em;">Trustee, Place 5</summary> -->

<!-- - Current Office Holder: Garrett Wilson<sup>[1](#fn1)</sup> -->
<!-- - First Gained Office: 09 Aug 2021 - Appointed to fill vacant seat<sup>[6](#fn6)</sup> -->
<!-- - Election History -->
<!-- 	- 07 May 2022 Election (Unopposed)<sup>[5](#fn5)</sup> -->

<!-- </details> -->

<br>
<span style="font-style: italic; font-size: 1.25em;">May 2026</span>
<details>
<summary style="font-size: 1.15em;">Trustee, Place 6</summary>

- Current Office Holder: Kristi Schmidt<sup>[1](#fn1)</sup>

</details>
<details>
<summary style="font-size: 1.15em;">Trustee, Place 7</summary>

- Current Office Holder: Rich Sena<sup>[1](#fn1)</sup>

</details>

<br>
<span style="font-style: italic; font-size: 1.25em;">May 2027</span>
<details>
<summary style="font-size: 1.15em;">Trustee, Place 1</summary>

- Current Office Holder: Carlin Friar<sup>[1](#fn1)</sup>

</details>
<details>
<summary style="font-size: 1.15em;">Trustee, Place 2</summary>

- Current Office Holder: Dallas Pipes<sup>[1](#fn1)</sup>

</details>
<details>
<summary style="font-size: 1.15em;">Trustee, Place 3</summary>

- Current Office Holder: Courtney Darter-Bruce<sup>[1](#fn1)</sup>

</details>


</details>
</div>

<br>

### Comfort ISD

<details>
  <summary style="font-size: 1.25em;">Important Election Dates</summary>

- **14 Jan 2026** - First Day to File for Place on Ballot  
- **13 Feb 2026** - Last Day to File for Candidacy
- **20 Apr 2026** - First Day of Early Voting by Personal Appearance
- **28 Apr 2026** - Last Day of Early Voting by Personal Appearance
- **02 May 2026** - Local Election

</details>

<details>
  <summary style="font-size: 1.25em;">Process to File</summary>

- Ensure you meet eligibility requirements: [Secretary of State - Qualifications](https://www.sos.state.tx.us/elections/laws/qualifications.shtml)
	- Basically...
		- Be a U.S. citizen living in the state for at least 12 months
		- Lived in the district at least 6 months
		- Don't be a felon or mentally incapacitated
- Complete a physical copy of the application: [Secretary of State - PDF](https://www.sos.state.tx.us/elections/forms/pol-sub/2-49f.pdf)
- Deliver completed application to Comfort ISD no later than <span style="text-decoration: underline;">**5:00pm, 13 Feb 2026**</span>.
	- Address: 232 High St, Comfort, TX 78013
- Contact for Questions:
	- Phone: 830-995-6400
	- Email: amanda.rust@comfortisd.net


</details>

<details>
  <summary style="font-size: 1.25em;">Positions Up for Election</summary>


- Nov 2026
	- District 1
		- Current Office Holder - Larry Thayn<sup>[11](#fn11)</sup>
	- District 2
		- Current Office Holder - Alison Judkins<sup>[11](#fn11)</sup>
	- District 3
		- Current Office Holder - Lilly Edwards<sup>[11](#fn11)</sup>
	- District 4
		- Current Office Holder - Shauna Stransky<sup>[11](#fn11)</sup>
	- District 7
		- Current Office Holder - Wesley Holekamp<sup>[11](#fn11)</sup>


</details>

<br/>

### City of Boerne

<details>
  <summary style="font-size: 1.25em;">Important Election Dates</summary>

- **14 Jan 2026** - First Day to File for Place on Ballot  
- **13 Feb 2026** - Last Day to File for Candidacy
- **20 Apr 2026** - First Day of Early Voting by Personal Appearance
- **28 Apr 2026** - Last Day of Early Voting by Personal Appearance
- **02 May 2026** - Local Election

</details>

<details>
  <summary style="font-size: 1.25em;">Process to File</summary>

- Review the [CoB Elections page](https://www.ci.boerne.tx.us/326/Elections)
	- This is by far the most informative and detailed elections page of any local government
	- Includes everything from previous election returns to publicly posted campaign finance reports from previous campaigns
	- Includes everything you need to file for candidacy 
- Determine if you live within the district boundaries of the position you would like to run for: [City of Boerne Council Districts](https://boerne.maps.arcgis.com/apps/dashboards/7ea9626985f345c1b882cb413b299c3b)
- Ensure you meet eligibility requirements: 
	- [Secretary of State - Qualifications](https://www.sos.state.tx.us/elections/laws/qualifications.shtml)
	- [City of Boerne Eligibility Requirements](https://www.ci.boerne.tx.us/326/Elections)
	- Basically...
		- Be at least 21
		- For city council, have lived in the district you're running for, for at least 6 months
		- For mayor, have lived in the city for at least 12 months
		- Be a U.S. citizen
		- Don't be a felon or mentally incapacitated
- Download a [Candidate Packet](https://www.ci.boerne.tx.us/DocumentCenter/View/23572/Candidate-Packet-General-Election) and/or [Application for Ballot](https://www.ci.boerne.tx.us/DocumentCenter/View/23579/Application-for-a-place-on-the-ballot---english) from the CoB website 
- Deliver completed application to CoB no later than <span style="text-decoration: underline;">**5:00pm, 13 Feb 2026**</span>.
	- Lori A. Carroll, City Secretary
	- City Hall, 447 N. Main St.
	- Phone: (830) 248-1525
	- Fax: (830) 249-9264
	- Email: lcarroll@ci.boerne.tx.us

</details> 

<details>
  <summary style="font-size: 1.25em;">Positions Up for Election</summary>

<div style="margin-left:20px">


<br>
<span style="font-style: italic; font-size: 1.25em;">May 2026</span>

<details>
<summary style="font-size: 1.15em;">Council Member, District 1</summary>

- Current Office Holder: Ty Wolosin<sup>[9](#fn9)</sup>

</details>
<details>
<summary style="font-size: 1.15em;">Council Member, District 3</summary>

- Current Office Holder: Quinten Scott<sup>[9](#fn9)</sup>

</details>
<details>
<summary style="font-size: 1.15em;">Council Member, District 5</summary>

- Current Office Holder: Joseph Macaluso<sup>[9](#fn9)</sup>

</details>

<br>
<span style="font-style: italic; font-size: 1.25em;">May 2027</span>


<details>
<summary style="font-size: 1.15em;">Mayor</summary>

- Current Office Holder: Frank Ritchie<sup>[7](#fn7)</sup>

</details>
<details>
<summary style="font-size: 1.15em;">Council Member, District 2</summary>

- Current Office Holder: Joe Bateman<sup>[9](#fn9)</sup>

</details>
<details>
<summary style="font-size: 1.15em;">Council Member, District 4</summary>

- Current Office Holder: Bret Bunker<sup>[9](#fn9)</sup>

</details>


</div>



</details>



<br/>

<!-- ### City of Fair Oaks Ranch -->

<!-- <details> -->
<!--   <summary style="font-size: 1.25em;">Important Election Dates</summary> -->

<!-- - **15 Jan 2025** - First Day to File for Place on Ballot   -->
<!-- - **14 Feb 2025** - Last Day to File for Candidacy -->
<!-- - **21 Apr 2025** - First Day of Early Voting by Personal Appearance -->
<!-- - **29 Apr 2025** - Last Day of Early Voting by Personal Appearance -->
<!-- - **03 May 2025** - Local Election -->

<!-- </details> -->

<!-- <details> -->
<!--   <summary style="font-size: 1.25em;">Process to File</summary> -->

<!-- - Review the [CoFOR Elections page](https://www.fairoaksranchtx.org/134/City-Elections) -->
<!-- 	- Includes required forms and publicly posted campaign finance reports from previous campaigns -->
<!-- - Ensure you meet eligibility requirements:  -->
<!-- 	- [Secretary of State - Qualifications](https://www.sos.state.tx.us/elections/laws/qualifications.shtml) -->
<!-- 	- [City of Fair Oaks Ranch Eligibility Requirements](https://www.fairoaksranchtx.org/134/City-Elections) -->
<!-- 	- Basically... -->
<!-- 		- Have lived in the city for at least 12 months -->
<!-- 		- Be a U.S. citizen -->
<!-- 		- Don't be a felon or mentally incapacitated -->
<!-- - Download a [Application for Ballot](https://fairoaksranchtx.org/DocumentCenter/View/5070/23-10-16-Application-for-a-Place-on-the-General-Election-Ballot-English) from the CoFOR website  -->
<!-- - Deliver completed application to CoFOR no later than <span style="text-decoration: underline;">**5:00pm, 14 Feb 2025**</span>. -->
<!-- 	- 7286 Dietz Elkhorn Rd, Fair Oaks Ranch, TX 78015 -->
<!-- 	- Phone: (210) 698-0900 -->
<!-- 	- Fax: (210) 698-3565 -->
<!-- 	- Email: citysec@fairoaksranchtx.org -->

<!-- </details>  -->

<!-- <details> -->
<!--   <summary style="font-size: 1.25em;">Positions Up for Election</summary> -->

<!-- <div style="margin-left:20px"> -->

<!-- <br> -->
<!-- <span style="font-style: italic; font-size: 1.25em;">May 2025</span> -->

<!-- <details> -->
<!-- <summary style="font-size: 1.15em;">Council Member, Place 3</summary> -->

<!-- - Current Office Holder: Ruben J. Olvera<sup>[11](#fn11)</sup> -->
<!-- - First Gained Office: 09 Dec 2023 Election -->
<!-- - Election History -->
<!-- 	- 09 Dec 2023 Election (Special Election to Fill Vacant Seat)<sup>[12](#fn12)</sup> -->
<!-- 		- Opposed by Vincent Caldarola -->
<!-- 		- Won 85.79% (489 votes) to 14.21% (81 votes) -->


<!-- </details> -->
<!-- <details> -->
<!-- <summary style="font-size: 1.15em;">Council Member, Place 4</summary> -->

<!-- - Current Office Holder: Laura Koerner<sup>[11](#fn11)</sup> -->
<!-- - First Gained Office:  -->
<!-- - Election History -->
<!-- 	- 07 May 2022 Election (Unopposed)<sup>[14](#fn14)</sup> -->
<!-- 	- 06 May 2019 Election (Unopposed)<sup>[13](#fn13)</sup> -->

<!-- </details> -->
<!-- <details> -->
<!-- <summary style="font-size: 1.15em;">Council Member, Place 5</summary> -->

<!-- - Current Office Holder: Scott Parker<sup>[11](#fn11)</sup> -->
<!-- - First Gained Office:  -->
<!-- - Election History -->
<!-- 	- 07 May 2022 Election (Unopposed)<sup>[14](#fn14)</sup> -->
<!-- 	- 01 May 2021 Election (Special Election to Fill Vacant Seat)<sup>[15](#fn15)</sup> -->
<!-- 	 	- Opposed by J.C. Taylor and Tim Corey -->
<!-- 		- Obtained 37.73% (907 votes) to Taylor's 49.42% (1,188 votes) and Corey's 12.85% (309 votes) -->
<!-- 		- Since no candidate obtained 50% of the vote, result triggered a runoff election -->
<!-- 		- Taylor withdrew his candidacy from the runoff election -->
<!-- 		- Per Texas Election Code, if a runoff candidate withdraws, the remaining candidate is considered to be elected -->

<!-- </details> -->

<!-- <br> -->
<!-- <span style="font-style: italic; font-size: 1.25em;">May 2026</span> -->

<!-- <details> -->
<!-- <summary style="font-size: 1.15em;">Council Member, Place 2</summary> -->

<!-- - Current Office Holder: Keith Rhoden<sup>[11](#fn11)</sup> -->

<!-- </details> -->
<!-- <details> -->
<!-- <summary style="font-size: 1.15em;">Council Member, Place 6</summary> -->

<!-- - Current Office Holder: Chesley Muenchow<sup>[11](#fn11)</sup> -->

<!-- </details> -->


<!-- <br> -->
<!-- <span style="font-style: italic; font-size: 1.25em;">May 2027</span> -->


<!-- <details> -->
<!-- <summary style="font-size: 1.15em;">Mayor</summary> -->

<!-- - Current Office Holder: Greg Maxton<sup>[11](#fn11)</sup> -->

<!-- </details> -->
<!-- <details> -->
<!-- <summary style="font-size: 1.15em;">Council Member, Place 1</summary> -->

<!-- - Current Office Holder: Emily Stroup<sup>[11](#fn11)</sup> -->

<!-- </details> -->

<!-- </div> -->

<!-- </details> -->





<br>
<br>
<!-- <h2>Campaigning 101</h2> -->
<!-- <hr> -->


<!-- I will update this with detail later, but long story short.... -->

<!-- - Figure out about how many votes you need -->
<!-- 	- Given generally low voter turnout, some races (e.g. CoB City Council) may only have a few hundred people vote  -->
<!-- - Figure out who votes -->
<!-- 	- You can get the data from the county elections office -->
<!-- 	- Determine who you know, that regularly vote, and make sure to talk to them about why you're the best candidate -->
<!-- 	- Determine who you know, that <span style="font-style: italic; text-decoration: underline;">do not</span> regularly vote, and make sure to talk to them about why they should -->
<!-- - Determine where the registered voters are... AND GO TALK TO THEM -->
<!-- 	- This really is the most important part, and it costs nothing but your own effort and whoever might want to help you -->
<!-- 		- Knock on doors -->
<!-- 			- It's not fun, but it helps -->
<!-- 			- BE RESPECTUL -->
<!-- 				- Don't bother people who clearly don't want to talk (e.g. "No Solicitation" sign, closed gates, etc) -->
<!-- 				- If someone wants to chat, chat but if they don't... GO AWAY -->
<!-- 		- Have friends host "meet the candidate" events at their house -->
<!-- 		- Participate in any forum and talk to any group that will have you -->
<!-- 			- Tea party -->
<!-- 			- Political Parties -->
<!-- 			- Boerne Star -->
<!-- 			- Rotary -->
<!-- 			- etc... -->
<!-- - My own opinion here, but it's a candidates obligation to make the case why they should be elected to the people. The people deserve to know, and it will help you get elected anyway (assuming you're a decent candidate...). You'll also get great feedback about what people think. They may not tell you how great you are, but if you're not willing to listen, then you're not a good fit for public office. -->

<hr>
<ol>
<li id="fn1"><p>“Board of Trustees.” Boerne Independent School District, [www.boerneisd.net/about/school-board-leadership](https://www.boerneisd.net/about/school-board-leadership). Accessed 14 Aug. 2025.</p></li>
<li id="fn2"><p>“Custom Minutes for February 27, 2023 at 5:00 PM - Regular Meeting.” Custom Minutes for February 27, 2023 at 5:00 PM - Regular Meeting - BoardBook Premier, [meetings.boardbook.org/Documents/CustomMinutesForMeeting/1350?meeting=567104](https://meetings.boardbook.org/Documents/CustomMinutesForMeeting/1350?meeting=567104). Accessed 14 Aug. 2025. </p></li>
<li id="fn3"><p>“Custom Minutes for March 2, 2020 at 5:00 PM - Special Meeting / Budget Workshop.” Custom Minutes for March 2, 2020 at 5:00 PM - Special Meeting / Budget Workshop - BoardBook Premier, [meetings.boardbook.org/Documents/CustomMinutesForMeeting/1350?meeting=218473](https://meetings.boardbook.org/Documents/CustomMinutesForMeeting/1350?meeting=218473). Accessed 14 Aug. 2025. </p></li>
<li id="fn4"><p>“May 6th, 2017 Local Election (City of Boerne and Boerne ISD).” Kendall County - Election Results, [https://results.enr.clarityelections.com/TX/Kendall/66832/186641/en/summary.html](https://results.enr.clarityelections.com/TX/Kendall/66832/186641/en/summary.html). Accessed 14 Aug. 2025. </p></li>
<li id="fn5"><p>“Custom Minutes for March 24, 2014 at 5:00 PM - Regular Meeting.” Custom Minutes for March 24, 2014 at 5:00 PM - Regular Meeting - BoardBook Premier, [meetings.boardbook.org/Public/Agenda/1350?meeting=217224](https://meetings.boardbook.org/Public/Agenda/1350?meeting=217224). Accessed 14 Aug. 2025. </p></li>
<li id="fn6"><p>“City Council.” City Council | Boerne, TX - Official Website, [www.ci.boerne.tx.us/77/City-Council](https://www.ci.boerne.tx.us/77/City-Council). Accessed 10 Oct. 2024. 
</p></li>
<li id="fn7"><p>“Ty Wolosin.” Staff Directory • Ty Wolosin, [www.ci.boerne.tx.us/directory.aspx?EID=14](https://www.ci.boerne.tx.us/directory.aspx?EID=14). Accessed 14 Aug. 2025.. </p></li>
<li id="fn8"><p>“May 4th, 2024 Joint Election (City of Boerne / City of Fair Oaks Ranch / Boerne ISD)” Kendall County - Election Results, [results.enr.clarityelections.com/TX/Kendall/121610/web.317647/#/summary](https://results.enr.clarityelections.com/TX/Kendall/117803/web.317647/#/summary). Accessed 14 Aug. 2025. 
</p></li>
<li id="fn9"><p>“Fanning, Timothy. “ Over before It Started: These Boerne City Council Members Win Re-Election by Default.” San Antonio Express News, San Antonio Express News, 9 Mar. 2022, [www.expressnews.com/news/local/article/Over-before-it-started-These-Boerne-city-council-16988840.php](https://www.expressnews.com/news/local/article/Over-before-it-started-These-Boerne-city-council-16988840.php). Accessed 10 Oct. 2024. 
</p></li>
<li id="fn10"><p>“Scott Moves, Resigns Dist. 3 Council Seat.” Boerne Star, Boerne Star, 16 July 2025,   [www.boernestar.com/article/11209,scott-moves-resigns-dist-3-council-seat](https://www.boernestar.com/article/11209,scott-moves-resigns-dist-3-council-seat). Accessed 14 Aug. 2025.
</p></li>
<li id="fn11"><p>ISD, Comfort. “Comfort ISD.” Comfort ISD - Election Information, [www.comfort.txed.net/33397_3](https://www.comfort.txed.net/33397_3). Accessed 14 Aug. 2025.
</p></li>

ISD, Comfort. “Comfort ISD.” Comfort ISD - Trustee Profiles, www.comfort.txed.net/33402_3. Accessed 14 Aug. 2025. 


<!-- <li id="fn11"><p>“City Council.” City Council | Fair Oaks Ranch, TX - Official Website, [www.fairoaksranchtx.org/63/City-Council](https://www.fairoaksranchtx.org/63/City-Council). Accessed 10 Oct. 2024.  -->
<!-- </p></li> -->
<!-- <li id="fn12"><p>“December 9th, 2023 Special Election (City of Fair Oaks Ranch)” Kendall County - Election Results, [results.enr.clarityelections.com/TX/Kendall/119273/web.317647/#/summary](https://results.enr.clarityelections.com/TX/Kendall/119273/web.317647/#/summary). Accessed 10 Oct. 2024.  -->
<!-- </p></li> -->
<!-- <li id="fn13"><p>“May 4th, 2019 Local Election (City of Boerne and Boerne ISD)” Kendall County - Election Results, [results.enr.clarityelections.com/TX/Kendall/95297/Web02.226438/#/](https://results.enr.clarityelections.com/TX/Kendall/95297/Web02.226438/#/). Accessed 10 Oct. 2024.  -->
<!-- </p></li> -->
<!-- <li id="fn14"><p>"Resolution 2022-07 Declaring Unopposed Candidates" City of Fair Oaks, [www.fairoaksranchtx.org/DocumentCenter/View/4112/Res-2022-07-Unopposed-Candidates-and-Canceling-Election](https:// -->
<!-- 	www.fairoaksranchtx.org/DocumentCenter/View/4112/Res-2022-07-Unopposed-Candidates-and-Canceling-Election]). Accessed 11 Oct. 2024.  -->
<!-- </p></li> -->
<!-- <li id="fn15"><p>City of Fair Oaks Ranch CITY COUNCIL SPECIAL MEETING Tuesday, May 11, 2021, [mccmeetings.blob.core.usgovcloudapi.net/fairoaktx-pubu/MEET-Packet-8b19512e7e9f4cf797642e7bc4688318.pdf](https://mccmeetings.blob.core.usgovcloudapi.net/fairoaktx-pubu/MEET-Packet-8b19512e7e9f4cf797642e7bc4688318.pdf). Accessed 11 Oct. 2024.  -->
</p></li>
</ol>




<div>
</div>