---
title: Comfort ISD Tax FAQs
---

<script src="lib/core-js-2.5.3/shim.min.js"></script>
<script src="lib/react-18.2.0/react.min.js"></script>
<script src="lib/react-18.2.0/react-dom.min.js"></script>
<script src="lib/reactwidget-1.0.0/react-tools.js"></script>
<script src="lib/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="lib/reactable-0.4.4/reactable.css" rel="stylesheet"/>
<script src="lib/reactable-binding-0.4.4/reactable.js"></script>

<div class="FAQ">

```{r plotly_hack, include = FALSE, echo=FALSE, message=FALSE, warning=FALSE}
# Both plot_ly and reactable require javascript and css libraries to be
# included in the HTML head. RMarkdown doesn't do this propoerly if the
# first use of these functions is in a loop or otehrwise nested. Loading
# These libraries and 'displaying' hidden output guarantees the correct
# libraries are included.

library(htmltools)
library(plotly)
library(reactable)
library(htmltools)
library(data.table)
source("assets/r/funcs_tables.R")
htmltools::tagList(plot_ly(x = rnorm(10), type = "histogram"))
print_table(data.table(a=1,b=2),"COW")
```



```{r init, echo=FALSE, message=FALSE, warning=FALSE}
library(readxl)
library(stringr)
library(fontawesome)
library(xml2)
library(dplyr)
library(plotly)

knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(cache = FALSE)

path.data <- file.path('data')


neighbor_districts <- data.table(CDN = c("130902", # Comfort ISD
                                         "130901", # Boerne ISD
                                         "010902", # Bandera ISD
                                         "133901", # Center Point ISD
                                         "133903", # Kerrville ISD
                                         "086901", # Fredericksburg ISD,
                                         "016902") # Blanco ISD
                                )


###
### Load Data
###

finance_summary <- read_excel(file.path(path.data,'2007-2023-summarized-financial-data-0.xlsx')) %>%
	data.table

tax_rates <- read_excel(file.path(path.data,'school-district-adopted-tax-rates.xlsx')) %>%
	data.table

jwt_taxes <- read_excel(file.path(path.data,'jwt_property_tax_history.xlsx')) %>%
	data.table 

levies_2023 <- read_excel(file.path(path.data,'2023-school-district-rates-levies.xlsx')) %>%
	data.table 

directory <- read.csv(file.path(path.data,'district_directory.csv')) %>%
  data.table 

# kcad_values <- read.csv(file.path(path.data,'KCAD_values.csv')) %>%
#   data.table %>% unique

cpi <- read.csv(file.path(path.data,'cpi.csv')) %>%
  data.table 


neighbor_districts[,County:=directory[District.Number %in% paste0("'",CDN)]$County.Name[1],by=CDN]
neighbor_districts[,Name:=directory[District.Number %in% paste0("'",CDN)]$District.Name[1],by=CDN]

###
### Munge Data
###

# Robin Hood


# Tax Rates

tmp <- t(tax_rates[`School District`=="COMFORT ISD"])
tmp <- tmp[3:nrow(tmp),]
CISD_tax_rates <- data.table(label=names(tmp),value=as.numeric(tmp))
CISD_tax_rates[,`Tax Year`:=as.integer(substr(label,6,9))-1]
CISD_tax_rates[,`School Year`:=paste0(`Tax Year`,'-',`Tax Year`+1),by=`Tax Year`]
CISD_combined_tax_rate <- CISD_tax_rates[,.(`Combined Tax Rate`=sum(value)),by=.(`Tax Year`,`School Year`)]
CISD_combined_tax_rate <- rbind(CISD_combined_tax_rate,
																list(`Tax Year`=2023, 
																		 `School Year`='2023-2024',
																		 `Combined Tax Rate`=levies_2023[`Taxing Unit Name`=="Comfort ISD"]$`Total Tax Rate`[1]))

tmp <- tax_rates[CDN %in% neighbor_districts$CDN]
years <- substr(names(tmp)[3:length(tmp)],1,4) %>% unique
CISD_neighbors_combined_tax_rate <- foreach(year=years, .combine='rbind') %do% {  
                                            cols <- grep(paste0("^",year),names(tmp),value=TRUE)
                                            tmp[,.(`Tax Year` = year, `Combined Tax Rate` = sum(.SD)), 
                                                .SD=cols, by="School District"]
}
CISD_neighbors_combined_tax_rate <- rbind(CISD_neighbors_combined_tax_rate,
                                          neighbor_districts[,.(`School District` = Name,
                                                                `Tax Year` = "2023",
                                                                `Combined Tax Rate` = levies_2023[toupper(`Taxing Unit Name`) == Name & toupper(`County Name`) == County]$`Total Tax Rate`[1]),
                                                             by=CDN][,.(`School District`,`Tax Year`,`Combined Tax Rate`)])
CISD_neighbors_combined_tax_rate <- rbind(CISD_neighbors_combined_tax_rate[`School District` != "COMFORT ISD"],
                                          CISD_neighbors_combined_tax_rate[`School District` == "COMFORT ISD"])


CISD_neighbors_combined_tax_rate[,Rank:=rank(-`Combined Tax Rate`),by=`Tax Year`]


# Per Student Funding

cols <- c("YEAR",
          "FALL SURVEY ENROLLMENT",
          "GEN FUNDS-TOTAL OPERATING REVENUE AND OTHER REVENUE",
          "ALL FUNDS-EQUITY TRANSFERS",
          "GEN FUNDS-TOTAL OPERATING REVENUE AND OTHER REVENUE AND RECAPTUR")
per_student_funding <- finance_summary[`DISTRICT NAME`=="COMFORT ISD",.SD,.SDcols=cols]
per_student_funding[,YEAR:=as.integer(YEAR)]
setkey(per_student_funding,"YEAR")
setkey(cpi,"factor_year")
per_student_funding <- cpi[per_student_funding]


# Tax Levies

# Data Requests

# 1) Appraised Valued and Taxing Jurisdictions (2010-2024):
#     - Property ID
#     - Year
#     - Appraised Value
#     - Taxable Value
#     - Property Taxing Jurisdictions
# 2) Adopted Tax Rates (2010-2024)



# kcad_values[year==2016,tax_rate:=CISD_combined_tax_rate[`Tax Year`==2016]$`Combined Tax Rate`]
# kcad_values[year==2024,tax_rate:=CISD_combined_tax_rate[`Tax Year`==2023]$`Combined Tax Rate`]
# kcad_values[year==2016,cpi:=1.3]
# kcad_values[year==2024,cpi:=1]
# kcad_values[,levy:=tax_rate*(appraisedValue/100)*cpi]


# tmp <- dcast(kcad_values, propertyId ~ year, value.var = "levy")
# tmp <- tmp[!is.na(`2016`)]
# tmp <- tmp[!is.na(`2024`)]

# quantile(tmp[,.((`2024`-`2016`))]$V1)
# median(tmp[,.((`2024`-`2016`))]$V1)
# median(tmp[,.((`2024`-`2016`)/`2016`)]$V1)

###
### Data Substitutions
###

tags_source <- list(CISD_tax = character())

# Cost of Recapture Since 2007
tags_source[["CISD"]] <- c(tags_source[["CISD"]],
															 `{{{TOTAL_RECAPTURE_2007_2023}}}` = finance_summary[`DISTRICT NAME`=="COMFORT ISD",
															 																									 scales::dollar_format()(sum(`ALL FUNDS-EQUITY TRANSFERS`))])
tags_source[["CISD"]] <- c(tags_source[["CISD"]],
                               `{{{AVG_RECAPTURE_PROP_BUDGET}}}` = finance_summary[`DISTRICT NAME`=="COMFORT ISD",
                               scales::label_percent()(median(`ALL FUNDS-EQUITY TRANSFERS`/`GEN FUNDS-TOTAL OPERATING REVENUE`))])


# Levied Taxes
tags_source[["CISD"]] <- c(tags_source[["CISD"]],
                               `{{{2023_COMBINED_RATE}}}` = levies_2023[`Taxing Unit Name`=="Comfort ISD",`M & O Rate` + `I & S Rate`][1])
tags_source[["CISD"]] <- c(tags_source[["CISD"]],
                               `{{{2023_LEVY}}}` = scales::label_comma()(levies_2023[`Taxing Unit Name`=="Comfort ISD",sum(`Calculated Levy`)]))
tags_source[["CISD"]] <- c(tags_source[["CISD"]],
                               `{{{2023_MARKET_VALUE}}}` = scales::label_comma()(levies_2023[`Taxing Unit Name`=="Comfort ISD",sum(`Market Value`)]))

# Tax Rate
tags_source[["CISD"]] <- c(tags_source[["CISD"]],
                               `{{{2005_TAX_RATE}}}` = CISD_combined_tax_rate[`Tax Year`==2005]$`Combined Tax Rate`)
tags_source[["CISD"]] <- c(tags_source[["CISD"]],
                               `{{{2023_TAX_RATE}}}` = CISD_combined_tax_rate[`Tax Year`==2023]$`Combined Tax Rate`)
tags_source[["CISD"]] <- c(tags_source[["CISD"]],
                               `{{{MEDIAN_TAX_RANK}}}` = CISD_neighbors_combined_tax_rate[`School District`=="COMFORT ISD", median(Rank)])
tags_source[["CISD"]] <- c(tags_source[["CISD"]],
                               `{{{2023_TAX_RANK}}}` = CISD_neighbors_combined_tax_rate[`School District`=="COMFORT ISD" & `Tax Year` == 2023]$Rank)

# Enrollment
tags_source[["CISD"]] <- c(tags_source[["CISD"]],
                               `{{{2023_LEVY_PER_STUDENT}}}` = scales::label_comma()(round(round(levies_2023[`Taxing Unit Name`=="Comfort ISD",sum(`Calculated Levy`)]/directory[District.Name=="COMFORT ISD"]$`District.Enrollment.as.of.Oct.2023`[1]))))

# Per-Student Funding 
tmp <- per_student_funding[,funding:=`GEN FUNDS-TOTAL OPERATING REVENUE AND OTHER REVENUE AND RECAPTUR`/`FALL SURVEY ENROLLMENT`*factor]
tags_source[["CISD"]] <- c(tags_source[["CISD"]],
                               `{{{2007_REVENUE_PER_STUDENT}}}` = scales::dollar_format()(tmp[factor_year==2007]$funding))
tags_source[["CISD"]] <- c(tags_source[["CISD"]],
                               `{{{2023_REVENUE_PER_STUDENT}}}` = scales::dollar_format()(tmp[factor_year==2023]$funding))

# finance_summary[,.SD,.SDcols=cols]
# names(finance_summary)

# # Tax Burden on JWT owned properties
# tags_source[["CISD"]] <- c(tags_source[["CISD"]],
# 															 `{{{JWT_TAX_MEDIAN}}}` = dcast(jwt_taxes, Address ~ `Appraisal Year`, value.var = "Real Tax Burden")[,(`2024`-`2016`)/`2016`] %>% median %>% round(.,2) %>% "*"(100) %>% paste0(.,"%"))
# tags_source[["CISD"]] <- c(tags_source[["CISD"]],
# 															 `{{{JWT_TAX_LOW}}}` = dcast(jwt_taxes, Address ~ `Appraisal Year`, value.var = "Real Tax Burden")[,(`2024`-`2016`)/`2016`] %>% min %>% round(.,2) %>% "*"(100) %>% paste0(.,"%"))
# tags_source[["CISD"]] <- c(tags_source[["CISD"]],
# 															 `{{{JWT_TAX_HIGH}}}` = dcast(jwt_taxes, Address ~ `Appraisal Year`, value.var = "Real Tax Burden")[,(`2024`-`2016`)/`2016`] %>% max %>% round(.,2) %>% "*"(100) %>% paste0(.,"%"))






###
### Load Questions
###

CISD_tax_questions <- as_list(read_xml(file.path(path.data,"FAQ_ComfortISD_Taxes.xml")))[[1]]

###
### Subsitute Tags
###

for (i in 1:length(CISD_tax_questions)) {
	CISD_tax_questions[[i]]$title <- unlist(CISD_tax_questions[[i]]$title)
	CISD_tax_questions[[i]]$answer <- unlist(CISD_tax_questions[[i]]$answer)
	CISD_tax_questions[[i]]$details <- unlist(CISD_tax_questions[[i]]$details)

	tags_dest <- unlist(str_extract_all(CISD_tax_questions[[i]]$answer, 
																		  "(\\{\\{\\{\\w+\\}\\}\\})", 
																		  simplify=FALSE))
	if (length(tags_dest)>0) {
		for (t in tags_dest) {
			CISD_tax_questions[[i]]$answer <- gsub(t,
																						 tags_source[["CISD"]][t],
																						 CISD_tax_questions[[i]]$answer,
																						 fixed=TRUE)
		}	
	}
}



# knitr::knit_hooks$set(drop2=function(before, options, envir) {
#     if (before) {
#         paste(
#             '<p>',
# 						'<a class="collapsed" data-toggle="collapse" href="#ce2">',
# 						paste0('<span class="if-collapsed">',toString(fontawesome::fa("square-caret-down")),'</span>'),
# 						'<span class="if-not-collapsed">-</span>',
# 						'</a>',
# 						'</p>',
# 						'<div class="collapse" id="ce2">',
# 						'<div class="card card-body">',  sep = "\n")
#     } else {
#         paste("</div>", "</div>", sep = "\n")
#     }
# })

display_plot <- function(p) {
	paste(
		'<div style="padding: 30px;">',
		htmltools::tagList(p),
		'</div>'
	)
}

display_question <- function(q,id,p=NULL,tab=NULL,tabwidth=700,rows=5) {
	out <- paste(
		paste0('<h3>',q$title,'</h3>'),
		'<div class="answer_wrapper">',
		trimws(gsub('\\s+', ' ', q$answer)),
		ifelse(is.null(p), '', display_plot(p)),
		'<p style="margin-top: 5px;">',
		paste0('<a class="collapsed" data-toggle="collapse" href="#',id,'">'),
		'<span class="if-collapsed">Show Details</span>',
		'<span class="if-not-collapsed">Hide Details</span>',
		'</a>',
		'</p>',
		paste0('<div class="collapse" id="',id,'">'),
		'<div class="card card-body answer-details">',
    trimws(gsub('\\s+', ' ', q$details)),
		ifelse(is.null(tab),'',print_table_html(tab, paste0("table_", id, sep=""), width=tabwidth, pagesize=rows)),
		'</div>',
		'</div>',
		'</div><br/>',
		sep = "\n"
	)
	cat(out)
}

```


```{r plots}
figures <- vector(mode = "list", length = length(CISD_tax_questions))
tables <- vector(mode = "list", length = length(CISD_tax_questions))


margins <- list(l = 50, r = 50,
                b = 50, t = 50,
                pad = 20)

btns_exclude <- c('sendDataToCloud', 'autoScale2d', 'resetScale2d', 'toggleSpikelines',
                  'hoverClosestCartesian', 'hoverCompareCartesian',
                  'zoom2d','pan2d','select2d','lasso2d','zoomIn2d','zoomOut2d')


###
### How Has Comfort ISD’s Tax Rate Changed Over Time?
###

tables[[3]] <- CISD_combined_tax_rate
figures[[3]] <- plot_ly(CISD_combined_tax_rate, x = ~`Tax Year`, y = ~`Combined Tax Rate`, 
											  type = 'scatter', name="Combined Tax Rate", mode = 'lines+markers',
												height=200)  %>%
  layout(title = "CISD Combined M&O and I&S Tax Rate 2005-2023", 
  			 xaxis=list(title="Year"),
 	  		 yaxis = list(title="Combined Tax Rate", 
 	  		 						  range=c(.75,2), 
 	  		 						  tickvals=list(.75,1,1.25,1.5,1.75,2),
 	  		 						  ticktext=list("0.75","1.00","1.25","1.50","1.75","2.00")),
         margin=margins) %>% 
  config(displayModeBar = TRUE,
         modeBarButtonsToRemove = btns_exclude)



###
### How Does Comfort ISD’s Tax Rate Compare to Neighboring Districts?
###


pdata <- copy(CISD_neighbors_combined_tax_rate)
pdata <- dcast(pdata, `Tax Year` ~ `School District`, value.var = "Combined Tax Rate")
ISDs <- names(pdata)[-1]
ISDs <- c(ISDs[ISDs!="COMFORT ISD"],"COMFORT ISD")
colors <- brewer.pal(n=7,"Set1")
colors[6] <- colors[7]
colors[7] <- "#D4AF37"
colors <- data.table(ISD=ISDs,color=colors)
setkey(colors, ISD)
fig <- plot_ly(pdata,
         type = "scatter",
         mode = "lines+markers",
         height = 300
       )  %>%
  layout(title = "CISD and Neighboring District's Tax Rates 2005-2023", 
         xaxis = list(title = "Year"),
         yaxis = list(title = "Combined Tax Rate", 
                      range = c(.75,2), 
                      tickvals = list(.75,1,1.25,1.5,1.75,2),
                      ticktext = list("0.75","1.00","1.25","1.50","1.75","2.00")),
         margin=margins,
         hovermode = 'x unified') %>% 
  config(displayModeBar = TRUE,
         modeBarButtonsToRemove = btns_exclude)
for (ISD in names(pdata)[-1]) {
  fig <- add_trace(fig, 
      y = pdata[[ISD]],
      x = ~`Tax Year`,
      name = ISD,
      mode = 'lines+markers',
      line = list( width = if(ISD=="COMFORT ISD") 5 else 2,
                   color = colors[ISD]$color ),
      marker = list( size = if(ISD=="COMFORT ISD") 12 else 7,
                     color = colors[ISD]$color,
                     line = list( width = 1, color="#999") ),
      opacity = if(ISD=="COMFORT ISD") 1 else .35
    )
}
figures[[4]] <- fig
tables[[4]] <- copy(pdata)


###
### How Has the Tax Burden for Comfort ISD’s Homeowners Changed Over Time?
###

# tables[[4]] <- jwt_taxes


###
### How Has Comfort ISD’s Revenue Per-Student Changed Over Time?
###

tables[[5]] <- per_student_funding

pdata <- per_student_funding
pdata[,per_student_rev:=`GEN FUNDS-TOTAL OPERATING REVENUE AND OTHER REVENUE`/`FALL SURVEY ENROLLMENT`*factor]
figures[[5]] <- plot_ly(pdata, x = ~factor_year, y = ~per_student_rev, 
                        type = 'scatter', name="Including\nRecapture", mode = 'lines+markers',
                        height=200)  %>%
  layout(title = "CISD Revenue Per Student (General Funds) 2007-2023", 
         xaxis=list(title="Year"),
         yaxis = list(title="Revenue Per Student\n(In 2024 Dollars)"),
         margin=margins) %>% 
  config(displayModeBar = TRUE,
         modeBarButtonsToRemove = btns_exclude)



# Noax <- list(
#   title = "",
#   zeroline = FALSE,
#   showline = FALSE,
#   showticklabels = FALSE,
#   showgrid = FALSE
# )


# mydata <- data.table(x=1:12, y=rnorm(10,mean=1:12, sd=2), y2=1:12) 


# goal_1 <- list(
#   xref = 'x',
#   yref= 'y',
#   x = 1,
#   y = 1,
#   xanchor = 'right',
#   yanchor = 'middle',
#   text = paste(2, '%'),
#     font = list(family = 'Arial bold',
#                 size = 12,
#                 color = 'rgba(67,67,67,1)'),
#   showarrow = FALSE)


# goal_2 <- list(
#   xref = 'x',
#   yref= 'y',
#   x = 12,
#   y = 12,
#   xanchor = 'left',
#   yanchor = 'middle',
#   text = paste(98, '%'),
#     font = list(family = 'Arial bold',
#                 size = 12,
#                 color = 'rgba(67,67,67,1)'),
#   showarrow = FALSE)



# a <- plot_ly(mydata, x = ~x, width=225, height=125) %>%
# 	add_trace(y=~y2, type = 'scatter', mode='lines', name='goal', line = list(color = 'black', width = 2))	%>%
# 	add_trace(y = ~y, name='performance', type = 'scatter', mode='lines', line = list(color = 'forestgreen', width = 3)) %>%
#   layout(paper_bgcolor = '#00000000',
# 			   plot_bgcolor = '#00000000', 
# 			   xaxis = Noax,
# 			 	 yaxis = Noax,
#  			 	 showlegend = FALSE,
#  			 	 annotations = list(goal_1,goal_2))


# ‘plot_bgcolor’: ‘rgba(0, 0, 0, 0)’,
# ‘paper_bgcolor’: ‘rgba(0, 0, 0, 0)’,


```


```{r, results='asis'}
i <- 0

for(q in CISD_tax_questions) {
	i <- i + 1
	if(is.null(figures[[i]]) & is.null(tables[[i]])) {
		display_question(q, paste0("Q",i))
	} else if (!is.null(figures[[i]]) & is.null(tables[[i]])) {
		display_question(q, paste0("Q",i),p=figures[[i]])			
	} else if (is.null(figures[[i]]) & !is.null(tables[[i]])) {
		display_question(q, paste0("Q",i),tab=tables[[i]],rows=nrow(tables[[i]]))			
	} else {
		display_question(q, paste0("Q",i),p=figures[[i]],tab=tables[[i]],rows=nrow(tables[[i]]))
	}
}
```


</div>