---
title: "Freidenker"
output: html_document
---

<style>
#header {
    display: none;
}
</style>


```{r plotly_hack, include = FALSE, echo=FALSE, message=FALSE, warning=FALSE}
# Both plot_ly and reactable require javascript and css libraries to be
# included in the HTML head. RMarkdown doesn't do this propoerly if the
# first use of these functions is in a loop or otehrwise nested. Loading
# These libraries and 'displaying' hidden output guarantees the correct
# libraries are included.

library(htmltools)
library(plotly)
library(reactable)
library(htmltools)
library(data.table)
source("assets/r/funcs_tables.R")
htmltools::tagList(plot_ly(x = rnorm(10), type = "histogram"))
print_table(data.table(a=1, b=2),"COW")

library(readxl)
library(stringr)
library(fontawesome)
library(xml2)
library(dplyr)
library(plotly)

knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(cache = FALSE)

path.data <- file.path("data")


display_post <- function(p, id) {
	out <- paste(
		paste0('<h2 style="margin-bottom: 0px; padding-bottom: 0px;">',
			   p$title,'</h2>'),
		'<p style="font-style:italic; color:#BBB">&nbsp;&nbsp;',
		p$date,
		'</p>',
		'<div class="post_wrapper">',
		'<p style="margin-top: 5px;">',
		trimws(gsub('\\s+', ' ', p$content)),
		'</p>',
		'</div>',
		'<hr/>',
		sep = "\n"
	)
	cat(out)
}

###
### Load Questions
###

blog_posts <- as_list(read_xml(file.path(path.data,"blog.xml")))[[1]]
```


<h3>Only the suppressed word is dangerous.</h3>
<h4 style="font-style: italic;">Karl Ludwig Börne</h4>
<span class="copyleft">Everything contained in this website, including text, data, analyses, and visualizations is available to download as reproducible source code from a public [GitHub repository](https://github.com/joetidwell/freidenker)</span>
<hr/>

<div id="blog_container">

```{r, results='asis'}
i <- 0

for(p in rev(blog_posts)) {
	i <- i + 1
	display_post(p, paste0("Post-", i))
}
```

</div>